/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms */



let firstNum = 1;
let secondNum = 2;
let thirdNum;
let sumOfEvenValuedTerms = 2;


while (sumOfEvenValuedTerms <= 4000000) {
  thirdNum = firstNum + secondNum;
  if(thirdNum % 2 === 0) {
    sumOfEvenValuedTerms += thirdNum;
  }

  firstNum = secondNum;
  secondNum = thirdNum;

}

console.log(sumOfEvenValuedTerms);
